<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LLLGMOJ" failures="4" tests="14" name="RetryMulitple" time="0.247" errors="0" timestamp="2023-05-27T20:12:27 IST">
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.012">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.009">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test1(Test001.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test2(Test001.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.009">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test002.Test1(Test002.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test2" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test002.Test2(Test002.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test3" time="0.003">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="runTimeRetryfailedTc.Test002" name="Test3" time="0.013"/>
</testsuite> <!-- RetryMulitple -->
